app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # add route from todo Application
    path('todo/', include('todo.urls'))
]


todo/urls.py
from django.urls import path

# import View dari todo Application
from .views import index_view, detail_view

app_name = 'todo'
urlpatterns = [
    # route untuk halaman daftar task
    path('', index_view, name='index'),
  	
# route untuk halaman detail task
    path('<int:task_id>', detail_view, name='detail')
]


todo/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.db import models


class Task(models.Model):
    # define status choices/options
    class TaskStatus(models.TextChoices):
        TODO = 'todo', _('Todo')
        IN_PROGRESS = 'in_progress', _('In Progress')
        CLOSED = 'closed', _('Closed')
    
    # define columns
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(
        max_length=20,
        choices=TaskStatus.choices,
        default=TaskStatus.TODO
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # define table name
        db_table = 'tasks'


todo/views.py
from django.shortcuts import render
from django.http import Http404

# import class Task dari file todo/models.py
from .models import Task


# Membuat View untuk halaman daftar task
def index_view(request):
    # Mengambil semua data task
    tasks = Task.objects.all()
    context = {
        'tasks': tasks
    }
    # parsing data task ke template todo/index.html dan merender nya
    return render(request, 'todo/index.html', context)


# Membuat View untuk halaman detail task
def detail_view(request, task_id):
    # Mengambil data task berdasarkan task ID
    try:
        task = Task.objects.get(pk=task_id)
        context = {
            'task': task
        }
    except Task.DoesNotExist:
        # Jika data task tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Task tidak ditemukan.")
    # parsing data task ke template todo/detail.html dan merendernya
    return render(request, 'todo/detail.html', context)


todo/templates/todo/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Todo App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Detail Task</h1>

      <div>
        <a href="{% url 'todo:index' %}" class="btn btn-success">Kembali ke Daftar</a>
      </div>

      <br>

      <div>
        <h2>{{ task.title }}</h2>
        
        <h4><span class="badge badge-warning">{{ task.status }}</span></h3>

        <p>
            {{ task.description }}
        </p>
      </div>
  </div>
 
  </body>
</html>



todo/templates/todo/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Todo App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Daftar Task</h1>

      <div>
        <a href="#" class="btn btn-success">Tambah Baru</a>
      </div>

      <br>

      <table class="table table-bordered table-striped">
          <thead>
              <tr>
                  <th width="5%">ID</th>
                  <th width="20%">Judul</th>
                  <th width="45%">Deskripsi</th>
                  <th width="5%">Status</th>
                  <th width="20%">Aksi</th>
              </tr>
          </thead>
          <tbody>
            <!-- daftar task-->
            {% if tasks %}
              {% for task in tasks %}
              <tr>
                  <td>{{ task.id }}</td>
                  <td>{{ task.title }}</td>
                  <td>{{ task.description }}</td>
                  <td>{{ task.status }}</td>
                  <td>
                    <a href="{% url 'todo:detail' task.id %}" class="btn btn-warning btn-sm">detail</a>
                      <a href="#" class="btn btn-primary btn-sm">ubah</a>
                      <a href="#" class="btn btn-danger btn-sm">hapus</a>
                  </td>
              </tr>
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="5">Data tidak ditemukan.</td>
              </tr>
            {% endif %}
          </tbody>
      </table>
  </div>
 
  </body>
</html>